Add setup.py
danswer-ai/danswer pull request #127
Opened 2023-07-02 18:45 UTC by Pipboyguy

Allows for a `pip install -e .[dev]`. 

This allows for:
- better linting
- beginner friendly IDE assistance

2023-07-03 23:02 UTC, Weves reviewed
Thanks for the change! The initial setup can definitely be made easier and we really appreciate you putting in the time and effort to help out here. 

As far as I know, `setup.py` is mostly considered legacy (e.g. if you look at the most up to date `pip` documentation, https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#, then you'll see `setup.py` marked as legacy). Is there a specific reason for using this over something more modern like `pyproject.toml` + something like the following for the `setup.py`:

```
#!/usr/bin/env python

import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

Or even more alternatively, using poetry (https://python-poetry.org/). I've never personally used poetry, but I've heard good things about it.

2023-07-04 10:24 UTC, Pipboyguy commented
@Weves updated to `pyproject.toml`

2023-07-09 00:10 UTC, yuhongsun96 commented
Hey @Pipboyguy,
Couple things if you don't mind:
1. [important] We don't want to duplicate the requirements, if we are moving towards a package management util, we should remove the files under requirements. This also means replacing the Docker builds which pull in the reqs and installs them into the container.
2. [optional] I think Poetry is pretty good as well, maybe you can do something like:
```
[tool.poetry]
name = "Danswer"
version = "0.1.0"
description = "Opensource Enterprise Question Answering"
license = "MIT"
# whatever else

[tool.poetry.dependencies]
python = "^3.8"
alembic = "1.10.4"
asyncpg = "0.27.0"
atlassian-python-api = "3.37.0"
beautifulsoup4 = "4.12.0"
# other dependencies

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
# whatever else
```
3. [minor] I know we don't do a great job of this currently, but it's also better to specify a min version of the dependencies rather than to pin it to an exact one.

If all this is too much hassle, don't worry about it, there are higher value items if you're looking to contribute, feel free to DM us.
But anyway, at the very least, we don't want to duplicate reqs in multiple places.

2023-07-09 00:12 UTC, yuhongsun96 requested changes
TLDR, let's avoid duplicate listing of requirements. Ideally move to poetry and make necessary changes to build processes.
But if it's too much of a hassle, it's ok to close this, there are higher priority stuff we can suggest!

Thanks!

2023-07-09 00:12 UTC, yuhongsun96 commented on backend/pyproject.toml
> +dependencies = [
Would want to avoid duplicating dependencies

2023-07-09 00:12 UTC, yuhongsun96 commented on backend/pyproject.toml
> +       "psycopg2==2.9.6",       "black==23.3.0",
minor neatness fix

2023-07-09 00:12 UTC, yuhongsun96 commented on backend/pyproject.toml
> +]
[nit] newline

2023-07-09 00:12 UTC, yuhongsun96 commented on backend/setup.py
> +    setuptools.setup()
[nit] newline

2023-07-11 15:29 UTC, closed without merging