Update Assistants Creation UI
danswer-ai/danswer pull request #1714
Opened 2024-06-26 18:30 UTC by pablodanswer

New assistants creation page UI

- Reorganization
- Padding
- Icons for dropdowns
- New dropdowns / layout components

2024-06-26 18:30 UTC, pablodanswer commented
<img width="1198" alt="Screenshot 2024-06-26 at 11 27 57 AM" src="https://github.com/danswer-ai/danswer/assets/171597620/db2512a8-1eda-4873-8575-f012290a00f6">

2024-07-03 16:37 UTC, Weves requested changes
Overall looks awesome! Left a couple small style comments. Two other quick things:

- Build is failing, seems to be an incorrect path somewhere?
- This may have already changed, but I slightly prefer the form being centered simply because this is how the other forms behave. If we want to move them to the left side, we can definitely have that discussion (I'm totally open to it), but for now I'd prefer to keep them consistent

2024-07-03 16:37 UTC, Weves commented on web/src/components/admin/connectors/Field.tsx
> +    <div className={`block font-medium base ${small ? "text-sm" : "tex-base"}`}>
`tex-base` -> `text-base`

2024-07-03 16:37 UTC, Weves commented on web/src/components/admin/connectors/Field.tsx
> +          <p className="bg-neutral-900 max-w-[200px] mb-1 text-sm rounded-lg p-1.5 text-white">
prefer using a named tailwind color here (both for neutral-900 and for white)

2024-07-03 16:37 UTC, Weves commented on web/src/components/admin/connectors/Field.tsx
> +              className="text-red-500 my-auto text-sm"
`text-red-500` -> `text-error`

2024-07-03 16:37 UTC, Weves commented on web/src/components/admin/connectors/Field.tsx
> +          className={`${noPadding ? "mr-3" : "mx-3"}  px-5 w-3.5 h-3.5 ${alignTop ? "mt-1" : "my-auto"}`}
nit: remove extra space

2024-07-03 17:11 UTC, Weves approved these changes

2024-07-03 17:11 UTC, merged