Cleaned up foreign key cleanup for user group deletion
danswer-ai/danswer pull request #2559
Opened 2024-09-25 17:57 UTC by hagen-danswer

## Description
[Provide a brief description of the changes in this PR]

## How Has This Been Tested?
[Describe the tests you ran to verify your changes]

## Accepted Risk
[Any know risks or failure modes to point out to reviewers]

## Related Issue(s)
[If applicable, link to the issue(s) this PR addresses]

## Checklist:
- [ ] All of the automated tests pass
- [ ] All PR comments are addressed and marked resolved
- [ ] If there are migrations, they have been rebased to latest main
- [ ] If there are new dependencies, they are added to the requirements
- [ ] If there are new environment variables, they are added to all of the deployment methods
- [ ] If there are new APIs that don't require auth, they are added to PUBLIC_ENDPOINT_SPECS
- [ ] Docker images build and basic functionalities work
- [ ] Author has done a final read through of the PR right before merge

2024-09-25 18:01 UTC, hagen-danswer commented on backend/ee/danswer/db/user_group.py
just moved these to the top of the file

2024-09-25 18:01 UTC, hagen-danswer commented on backend/ee/danswer/db/user_group.py
>  def prepare_user_group_for_deletion(db_session: Session, user_group_id: int) -> None:
This function now cleans up all 7 fk relationships for usergroups:

- credential
- user
- llm_provider
- document_set
- token_rate_limit
- persona
- connector_credential_pair

2024-09-25 18:01 UTC, hagen-danswer commented on backend/ee/danswer/db/user_group.py
> +def delete_user_group(db_session: Session, user_group: UserGroup) -> None:
removed duplicate fk cleanup  so this function is now super simple (but it assumes fk cleanup has already been performed

2024-09-25 18:01 UTC, hagen-danswer commented on backend/ee/danswer/db/user_group.py
> -def delete_user_group(db_session: Session, user_group: UserGroup) -> None:
this function was moved up to be near the fk_cleanup function

2024-09-25 19:52 UTC, rkuo-danswer requested changes
Possible to add tests for these relationships?  As an example I just injected an entry in the DB for connector deletion ... maybe we could do something similar here.

2024-09-25 19:52 UTC, rkuo-danswer commented on backend/ee/danswer/db/user_group.py
> +    db_session.delete(user_group)
The old function had an explicit comment about flushing, but that doesn't seem to be getting handled here.  Any reason why?

2024-09-26 03:37 UTC, rkuo-danswer approved these changes

2024-09-26 03:52 UTC, merged