Improved api key forms + fix non-submittable azure
danswer-ai/danswer pull request #2654
Opened 2024-10-01 22:38 UTC by pablodanswer

## Description
[Provide a brief description of the changes in this PR]

## How Has This Been Tested?
[Describe the tests you ran to verify your changes]

## Accepted Risk
[Any know risks or failure modes to point out to reviewers]

## Related Issue(s)
[If applicable, link to the issue(s) this PR addresses]

## Checklist:
- [ ] All of the automated tests pass
- [ ] All PR comments are addressed and marked resolved
- [ ] If there are migrations, they have been rebased to latest main
- [ ] If there are new dependencies, they are added to the requirements
- [ ] If there are new environment variables, they are added to all of the deployment methods
- [ ] If there are new APIs that don't require auth, they are added to PUBLIC_ENDPOINT_SPECS
- [ ] Docker images build and basic functionalities work
- [ ] Author has done a final read through of the PR right before merge

2024-10-02 18:00 UTC, Weves requested changes

2024-10-02 18:00 UTC, Weves commented on web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
> +                  "Enableasdf"
we may want to remove this

2024-10-02 18:19 UTC, pablodanswer commented on web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
> +                  "Enableasdf"
This is far

2024-10-05 02:29 UTC, Weves approved these changes

2024-10-05 02:29 UTC, merged