upgraded claude model strings
danswer-ai/danswer pull request #2876
Opened 2024-10-22 21:03 UTC by hagen-danswer

2024-10-22 21:10 UTC, pablodanswer requested changes
Looks good but

2024-10-22 21:10 UTC, pablodanswer commented on web/src/lib/llm/utils.ts
>    "claude-3-haiku-20240307",
Users that have previously set their default model should still have access to image input

2024-10-22 21:10 UTC, pablodanswer commented on backend/danswer/llm/llm_provider_options.py
> +            default_model="claude-3-5-sonnet-20241022",
Watch out for context length issues - unless we bump our LiteLLM version (when they add "support" for this model), will use default max tokens (which is super low, something like `4096`)

2024-10-22 23:00 UTC, hagen-danswer commented
Waiting for tagged litellm version:
[Repo](https://github.com/BerriAI/litellm/tags)

2024-10-25 04:02 UTC, LostVector approved these changes

2024-10-25 04:02 UTC, LostVector commented on web/src/lib/hooks.ts
> +  "claude-3-5-sonnet-20241022": "Claude 3.5 Sonnet (New)",
seems possible we might need to rename (new) later but i suppose that's easily fixable if it happens

2024-10-26 00:11 UTC, pablodanswer approved these changes

2024-10-26 00:38 UTC, merged