initial removal of locks!
danswer-ai/danswer pull request #3017
Opened 2024-10-31 23:19 UTC by pablodanswer

## Description
[Provide a brief description of the changes in this PR]

## How Has This Been Tested?
[Describe the tests you ran to verify your changes]

## Accepted Risk (provide if relevant)
N/A

## Related Issue(s) (provide if relevant)
N/A

## Mental Checklist:
- All of the automated tests pass
- All PR comments are addressed and marked resolved
- If there are migrations, they have been rebased to latest main
- If there are new dependencies, they are added to the requirements
- If there are new environment variables, they are added to all of the deployment methods
- If there are new APIs that don't require auth, they are added to PUBLIC_ENDPOINT_SPECS
- Docker images build and basic functionalities work
- Author has done a final read through of the PR right before merge

## Backporting (check the box to trigger backport action)
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag the patches.
- [ ] This PR should be backported (make sure to check that the backport attempt succeeds)

2024-11-01 20:14 UTC, rkuo-danswer requested changes

2024-11-01 20:14 UTC, rkuo-danswer commented on backend/danswer/background/celery/apps/app_base.py
> +        time.monotonic()
This seems like a no op?

2024-11-01 20:14 UTC, rkuo-danswer commented on backend/scripts/dev_run_background_jobs.py
> +        "danswer.background.celery.apps.beat",
we should still use the versioned apps stub for consistency, but just point it at the single beat app.  Don't want someone to have to think about what entrypoint to use for the celery apps.

2024-11-01 20:18 UTC, pablodanswer commented on backend/danswer/background/celery/apps/app_base.py
> +        time.monotonic()
Good catch!

2024-11-03 17:50 UTC, trial-danswer approved these changes

2024-11-03 17:51 UTC, merged