multiple slackbot support
danswer-ai/danswer pull request #3077
Opened 2024-11-06 22:48 UTC by hagen-danswer

2024-11-19 23:01 UTC, rkuo-danswer requested changes

2024-11-19 23:01 UTC, rkuo-danswer commented on backend/alembic/versions/4ee1287bd26a_add_multiple_slack_bot_support.py
> +        sa.ForeignKeyConstraint(
i think sqlalchemy and other generators have a common naming convention for foreign key constraints, we should follow that.

2024-11-19 23:01 UTC, rkuo-danswer commented on web/src/components/EditableTextAreaDisplay.tsx
> +    if (e.key === "Enter") {
Does this if statement make sense?

2024-11-19 23:01 UTC, rkuo-danswer commented on web/src/components/EditableStringFieldDisplay.tsx
> +    if (e.key === "Enter") {
Does this if statement make sense?

2024-11-19 23:01 UTC, rkuo-danswer commented on web/src/components/BackButton.tsx
> +        } else if (routerOverride) {
is this the proper way to do this?

2024-11-19 23:01 UTC, rkuo-danswer commented on web/src/app/admin/documents/sets/page.tsx
>          into a single bundle. These can then be used as filter when performing
as "a" filter.

2024-11-19 23:01 UTC, rkuo-danswer commented on web/src/app/admin/documents/sets/page.tsx
> +        of information the bot searches over when answering in a specific
This text seems overly wordy but mostly not in scope.

2024-11-19 23:01 UTC, rkuo-danswer commented on web/src/app/admin/bots/new/page.tsx
> +        slack_bot_id={slack_bot_id}
naming style is inconsistent

2024-11-19 23:01 UTC, rkuo-danswer commented on backend/danswer/db/slack_channel_config.py
> +    return f"{SLACK_BOT_PERSONA_PREFIX}{channel_name}"
this was joining with a dash before, did we want to leave that out?

2024-11-19 23:01 UTC, rkuo-danswer commented on backend/danswer/server/manage/models.py
> +class SlackBot(BaseModel):
would be good to comment what this model is / used for

2024-11-19 23:01 UTC, rkuo-danswer commented on backend/danswer/danswerbot/slack/listener.py
> +        logger.debug(
doesn't seem super useful even for debugging once the problem has been figured out.

2024-11-19 23:01 UTC, rkuo-danswer commented on backend/danswer/danswerbot/slack/listener.py
> +                search_settings = get_current_search_settings(db_session)
does the slack bot need to warm up the model server? I feel like the celery workers already do this.

2024-11-19 23:01 UTC, rkuo-danswer commented on backend/danswer/danswerbot/slack/listener.py
> +        if (
this if statement and nested ones are pretty complicated ... any way to simplify?

2024-11-19 23:01 UTC, rkuo-danswer commented on backend/danswer/danswerbot/slack/listener.py
> +            asyncio.run(client.close())
no if client needed here?

2024-11-19 23:10 UTC, hagen-danswer commented on web/src/components/BackButton.tsx
> +        } else if (routerOverride) {
chris seemed okay with it lol

2024-11-19 23:12 UTC, hagen-danswer commented on web/src/app/admin/documents/sets/page.tsx
> +        of information the bot searches over when answering in a specific
agreed! has been reduced

2024-11-19 23:13 UTC, hagen-danswer commented on backend/danswer/db/slack_channel_config.py
> +    return f"{SLACK_BOT_PERSONA_PREFIX}{channel_name}"
yes, its just one name per now

2024-11-19 23:14 UTC, hagen-danswer commented on backend/danswer/danswerbot/slack/listener.py
> +            asyncio.run(client.close())
no

2024-11-19 23:18 UTC, hagen-danswer commented on backend/danswer/danswerbot/slack/listener.py
> +        if (
I greatly simplified it, good thought

2024-11-20 00:10 UTC, rkuo-danswer approved these changes

2024-11-20 02:12 UTC, merged